package com.expense.mvc.model.entity;

// Generated Jul 12, 2012 1:19:22 PM by Hibernate Tools 3.4.0.CR1. Customized by Bala.
//Customization - 1. Field level Annotations
//				- 2. Extends Entity for ToString Implementation.

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.expense.utils.FormatUtils;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "BILL")
public class Bill extends com.expense.mvc.model.BaseEntity implements java.io.Serializable, Comparable<Bill> {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BILL_ID", unique = true, nullable = false)
	private Integer billId;

	@Column(name = "DATA_KEY", nullable = false)
	private int dataKey;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ACCOUNT_ID")
	private Account account;

	@Column(name = "CREATED_DT")
	private String strCreatedDt;

	@Column(name = "BILL_DT")
	private String strBillDt;

	@Column(name = "DUE_DT")
	private String strDueDt;

	@Column(name = "BILL_AMT", precision = 11)
	private Double billAmt;

	@Column(name = "BILL_BALANCE", precision = 11)
	private Double billBalance;

	@Column(name = "Bill_PAID_DT")
	private String strBillPaidDt;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAY_TRAN_ID")
	private Transaction payTran;

	@Column(name = "STATUS", length = 1)
	private Character status;

	public enum Status {
		OPEN('O'), CLOSED('C');

		public char status;

		private Status(char status) {
			this.status = status;
		}
	}

	@SuppressWarnings("deprecation")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fromBill")
	@Cascade({ CascadeType.DELETE_ORPHAN, CascadeType.ALL })
	private Set<Transaction> transForFromBill = new HashSet<Transaction>(0);

	@SuppressWarnings("deprecation")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toBill")
	@Cascade({ CascadeType.DELETE_ORPHAN, CascadeType.ALL })
	private Set<Transaction> transForToBill = new HashSet<Transaction>(0);

	@SuppressWarnings("deprecation")
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "lastBill")
	@Cascade({ CascadeType.DELETE_ORPHAN, CascadeType.ALL })
	private Account accountHavingLastBill;

	@SuppressWarnings("deprecation")
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "openBill")
	@Cascade({ CascadeType.DELETE_ORPHAN, CascadeType.ALL })
	private Account accountHavingOpenBill;

	public Bill() {
	}

	public Integer getBillId() {
		return billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	public int getDataKey() {
		return dataKey;
	}

	public void setDataKey(int dataKey) {
		this.dataKey = dataKey;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getStrCreatedDt() {
		return strCreatedDt;
	}

	public void setStrCreatedDt(String strCreatedDt) {
		this.strCreatedDt = strCreatedDt;
	}

	public String getStrBillDt() {
		return strBillDt;
	}

	public void setStrBillDt(String strBillDt) {
		this.strBillDt = strBillDt;
	}

	public String getStrDueDt() {
		return strDueDt;
	}

	public void setStrDueDt(String strDueDt) {
		this.strDueDt = strDueDt;
	}

	public Double getBillAmt() {
		return billAmt;
	}

	public void setBillAmt(Double billAmt) {
		this.billAmt = billAmt;
	}

	public Double getBillBalance() {
		return billBalance;
	}

	public void setBillBalance(Double billBalance) {
		this.billBalance = billBalance;
	}

	public String getStrBillPaidDt() {
		return strBillPaidDt;
	}

	public void setStrBillPaidDt(String strBillPaidDt) {
		this.strBillPaidDt = strBillPaidDt;
	}

	public Transaction getPayTran() {
		return payTran;
	}

	public void setPayTran(Transaction payTran) {
		this.payTran = payTran;
	}

	public Set<Transaction> getTransForFromBill() {
		return transForFromBill;
	}

	public void setTransForFromBill(Set<Transaction> transForFromBill) {
		this.transForFromBill = transForFromBill;
	}

	public Set<Transaction> getTransForToBill() {
		return transForToBill;
	}

	public void setTransForToBill(Set<Transaction> transForToBill) {
		this.transForToBill = transForToBill;
	}

	public Account getAccountHavingLastBill() {
		return accountHavingLastBill;
	}

	public void setAccountHavingLastBill(Account accountHavingLastBill) {
		this.accountHavingLastBill = accountHavingLastBill;
	}

	public Account getAccountHavingOpenBill() {
		return accountHavingOpenBill;
	}

	public void setAccountHavingOpenBill(Account accountHavingOpenBill) {
		this.accountHavingOpenBill = accountHavingOpenBill;
	}

	public Date getCreatedDt() {
		try {
			return FormatUtils.yyyyMMddHHmmss.parse(strCreatedDt);
		} catch (Exception e) {
			return new Date(0);
		}
	}

	public void setCreatedDt(Date createdDt) {
		strCreatedDt = FormatUtils.yyyyMMddHHmmss.format(createdDt);
	}

	public Date getBillDt() {
		try {
			return FormatUtils.yyyyMMdd.parse(strBillDt);
		} catch (Exception e) {
			return new Date(0);
		}
	}

	public void setBillDt(Date billDt) {
		strBillDt = FormatUtils.yyyyMMdd.format(billDt);
	}

	public Date getDueDt() {
		try {
			return FormatUtils.yyyyMMdd.parse(strDueDt);
		} catch (Exception e) {
			return new Date(0);
		}
	}

	public void setDueDt(Date dueDt) {
		strDueDt = FormatUtils.yyyyMMdd.format(dueDt);
	}

	public Date getBillPaidDt() {
		try {
			return FormatUtils.yyyyMMdd.parse(strBillPaidDt);
		} catch (Exception e) {
			return new Date(0);
		}
	}

	public void setBillPaidDt(Date billPaidDt) {
		if (billPaidDt != null) {
			strBillPaidDt = FormatUtils.yyyyMMdd.format(billPaidDt);
		}
	}

	public Character getStatus() {
		return status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public boolean isUnpaid() {
		return billBalance > 0;
	}

	public boolean isOpen() {
		return status == Status.OPEN.status;
	}

	@Override
	public int compareTo(Bill o) {
		return getDueDt().compareTo(o.getDueDt());
	}
}
